### ISSUE TITLE
Contribute this back to org-mode?

### ISSUE THREAD

**Issue by phil-s** [Fuco1/org-radiobutton#1]
It seems like the logical thing to do, no?

**Comment by Fuco1** [comment]
@phil-s I've tried several times to contribute to org mode and it never worked out.  I am unable to work with mailing lists and I am not willing to put time into configuring that or learning how it works.

Feel free to take the code and submit it if you know how that works.  The licence should be fine, I've signed the Gnu/Emacs CLA so my code can be distributed with Emacs.

**Comment by Fuco1** [comment]
Similar feature inspired by this has now been included in org.
